version: "3.9"

services:
  socket:
    image: tecnativa/docker-socket-proxy
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      AUTH: 1
      BUILD: 1
      CONTAINERS: 1
      NETWORKS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      SESSION: 1
      CONFIGS: 1
      SYSTEM: 1

  runner:
    build:
      context: .
    environment:
      DOCKER_HOST: socket:2376
      ACCESS_TOKEN_FILE: /run/secrets/github_access_token
      LABELS: node1,node1,nodea,python1
      ORGANIZATION: sisitech

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./access-token/token:/run/secrets/github_access_token:ro
      - ./access-token/labels:/run/secrets/labels:ro
